version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/invoice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/derive"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/descriptors"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/psbt"
    schedule:
      interval: "weekly"
