[package]
name = "bp-wallet"
version = "0.10.0"
description = "Descriptor wallet supporting RGB and other bitcoin protocol applications"
keywords = ["bitcoin", "wallet", "descriptor-wallet", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://lnp-bp.org"
repository = "https://github.com/BP-WG/bp-wallet"
rust-version = "1.60" # Due to rust-amplify
edition = "2021"
license = "Apache-2.0"

[lib]
name = "bp"

[[bin]]
name = "bp"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
amplify = "4.0.0-beta.17"
clap = { version = "4.1.6", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "2.2.0", optional = true }
toml = { version = "0.7.2", optional = true }
serde-jsonlines = { version = "0.4.0", optional = true }

[features]
default = []
all = ["cli", "serde"]
cli = ["clap", "serde", "serde-jsonlines", "toml"]
serde = ["serde_crate", "serde_with"]
