[package]
name = "bp-wallet"
version = "0.11.0"
description = "Modern, minimalistic & standard-compliant cold wallet library"
keywords = ["bitcoin", "wallet", "descriptor-wallet", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://lnp-bp.org"
repository = "https://github.com/BP-WG/bp-wallet"
rust-version = "1.60" # Due to rust-amplify
edition = "2021"
license = "Apache-2.0"

[lib]
name = "bp"

[dependencies]
amplify = "4.0.0"
secp256k1 = "0.27.0"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde"]
serde = ["serde_crate"]
