[workspace]
members = ["std", "descriptors", "psbt", "."]
resolver = "2"

[workspace.package]
version = "0.11.0"
keywords = ["bitcoin", "wallet", "descriptors", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://lnp-bp.org"
repository = "https://github.com/BP-WG/bp-wallet"
rust-version = "1.67" # Due to strict encoding library
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.2.0"
bitcoin_hashes = "0.13.0"  # TODO: Remove and replace with commit_verify
bech32 = "0.9.1"
bp-consensus = "0.10.10"
indexmap = "2.0.0"
serde_crate = { package = "serde", version = "1", features = ["derive"] }

[patch.crates-io]
amplify_derive = { git = "https://github.com/rust-amplify/amplify-derive", branch = "wrapper" }
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "develop" }
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }
