[package]
name = "bp-std"
version = { workspace = true }
description = "Modern, minimalistic & standard-compliant cold wallet library"
keywords = { workspace = true }
categories = { workspace = true }
readme = "../README.md"
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "bpstd"

[dependencies]
amplify = { workspace = true }
bitcoin_hashes = "0.12.0"
bech32 = { workspace = true }
bp-primitives = { workspace = true }
serde_crate = { workspace = true, optional = true }

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "bp-primitives/serde"]
